local UILibrary = loadstring(game:HttpGet("https://raw.githubusercontent.com/vaxtalastus-web/Casserus-UI-Library-RBX/refs/heads/main/source.lua"))()
local MyWindow = UILibrary:CreateWindow("My Awesome GUI")
local mainTab = MyWindow:CreateTab("Main")
local settingsTab = MyWindow:CreateTab("Settings")
local creditsTab = MyWindow:CreateTab("Credits")
mainTab:CreateButton("Print Message", function()
    print("Button was clicked!")
end)
local isToggled = false
mainTab:CreateToggle("Toggle Something", function(state)
    isToggled = state
    print("Toggle is now:", state)
end)
settingsTab:CreateSlider("Speed", 10, 100, 25, function(value)
    print("Slider value:", value)
end)
settingsTab:CreateKeybind("Action Key", function(key)
    print(key.Name, "was pressed!")
end)
creditsTab:CreateButton("Made by: You!", function()
    print("Thanks for using the library!")
end)